CinemaHall:
  tableName: 'cinema_hall'
  properties:
    - { name: 'id', type: 'int', fieldName: 'id' }
    - { name: 'name', type: 'string', fieldName: 'name' }
    - { name: 'cinemaHallPlaceRelation', type: 'Nikolai\Php\Domain\Collection\LazyLoadCollection', fieldName: 'cinema_hall_id', tableName: 'cinema_hall_place_relation', itemCollectionClass: 'Nikolai\Php\Domain\Entity\CinemaHallPlaceRelation' }

Place:
  tableName: 'place'
  properties:
    - { name: 'id', type: 'int', fieldName: 'id' }
    - { name: 'row', type: 'int', fieldName: 'row' }
    - { name: 'col', type: 'int', fieldName: 'col' }
    - { name: 'cinemaHallPlaceRelation', type: 'Nikolai\Php\Domain\Collection\LazyLoadCollection', fieldName: 'place_id', tableName: 'cinema_hall_place_relation', itemCollectionClass: 'Nikolai\Php\Domain\Entity\CinemaHallPlaceRelation' }

CinemaHallPlaceRelation:
  tableName: 'cinema_hall_place_relation'
  properties:
    - { name: 'id', type: 'int', fieldName: 'id' }
    - { name: 'cinemaHall', type: 'Nikolai\Php\Domain\Entity\CinemaHall', fieldName: 'cinema_hall_id', tableName: 'cinema_hall' }
    - { name: 'place', type: 'Nikolai\Php\Domain\Entity\Place', fieldName: 'place_id', tableName: 'place' }
